### PR TITLE
Fix "npm install" to work if .npmrc is at per-project level

### PR DESCRIPTION
**Pull request by hmak3d**
AFAIK this is another approach for https://github.com/unicode-org/full-icu-npm/pull/40

### CODE REVIEW

**Comment by srl295** [comment]
@hmak3d seems simpler… @dfrankland can you comment on this approach?

**Comment by srl295** [comment]
@hmak3d @dfrankland ^ any comments?

**Comment by dfrankland** [comment]
Sorry, this solution does not work. I've created a full reproduction that tries to install `full-icu`, this fix, and the fix in #40:
https://github.com/dfrankland/full-icu-npm-npmrc-repro

Only #40 fixes the problem.

**Comment by srl295** [comment]
closed in favor of #40

**Pull request closed without merging**
