### PR TITLE
Fix #4

### LINKED ISSUE #4: node-full-icu-path buggy
the tool (#3) uses CWD (as coded) and it should somehow check its module's path.

### PR DESCRIPTION
**Pull request by niklaskorz**
Bug fix for issue #4

### CODE REVIEW

**Comment by julien-f** [comment]
Hi, when will this be released?

**Comment by srl295** [comment]
@julien-f sorry-will do today

**Comment by srl295** [comment]
@julien-f done `full-icu@1.2.1`

**Comment by julien-f** [comment]
Thank you :)

**Pull request merged**
